### ISSUE TITLE
Create a docker image

### ISSUE THREAD

**Issue by crazynds** [axeloz/filesharing#43]
I really liked your system, I think there's just one way left to go up to production easily, what do you think about creating a docker image? I can help with that if needed.
If you find the idea interesting, let me know and I can create a pull request.

**Comment by axeloz** [comment]
Hello @crazynds , 

Glad you enjoy Filesharing. Having a Docker image is a good idea. I actually started to work on it some weeks ago but left it aside. Feel free to make a pull request. If the image has to be pushed to Docker hub, I have created the axeloz/filesharing repo. 
Thanks

**Comment by axeloz** [comment]
@crazynds I pushed my version of Dockerfile: https://github.com/axeloz/filesharing/commit/687c6f1760735fbc3f36161f65dff8dc738a6dae
Working but probably missing some stuff (including exposing artisan for commands or ENV VARS for settings). 
Let me know. 
Thanks

**Comment by axeloz** [comment]
@crazynds you may now check here: https://hub.docker.com/r/axeloz/filesharing
Waiting for your feedbacks 👍

**Comment by crazynds** [comment]
@axeloz 
I tested the image and at first it is working normally. I sent a pull request #44 to add a template using docker-compose to the documentation.
Would it be possible to create an image with the latest tag? I believe it would be better than always having to update the version manually.

**Comment by axeloz** [comment]
Thanks @crazynds 
Merged

**Comment by axeloz** [comment]
Good point about the latest tag @crazynds 
Done, automatic build and push to Docker hub of `filesharing:<version>` and `filesharing:latest`
