### ISSUE TITLE
Creating Users (docker image) + Upload Issue

### ISSUE THREAD

**Issue by FuckingToasters** [axeloz/filesharing#48]
Hello, i'd like to make an administrative user (my own) to manage the application via an admin dashboard
On other docker containers i deloyd so far the first user created automatically got admin privileges, for filesharing there don't seem to be an register page.

It would also be nice, if users can register accounts for themselves.

When pressing the crete app bundle button on my instance, nothing seem to happen.

Regards,
FuckingToasters

**Comment by axeloz** [comment]
Hey @FuckingToasters. OK you are mixing feature request and bug report 😉

Let's start with the issue. You cannot start a new bundle? Does it work for you from the demo (https://filesharing.box.webinno.fr/)?
On your instance, can you open the Browser Console (https://appuals.com/open-browser-console/) and check in the "Console" tab if there is any red error when you click the "New bundle" button? 
Paste the errors here please

Next, there is no dashboard on filesharing yet. You are right, there is no default user for security reasons (half or more of the admins won't change the default password, plus there is no easy way to do it anyways). 
Filesharing is built with simplicity in mind. But I suppose that a dashboard would make sense.

**Comment by FuckingToasters** [comment]
> Hey @FuckingToasters. OK you are mixing feature request and bug report 😉
> 
> Let's start with the issue. You cannot start a new bundle? Does it work for you from the demo (https://filesharing.box.webinno.fr/)? On your instance, can you open the Browser Console (https://appuals.com/open-browser-console/) and check in the "Console" tab if there is any red error when you click the "New bundle" button? Paste the errors here please
> 
> Next, there is no dashboard on filesharing yet. You are right, there is no default user for security reasons (half or more of the admins won't change the default password, plus there is no easy way to do it anyways). Filesharing is built with simplicity in mind. But I suppose that a dashboard would make sense.

Oh sorry mb for mixing it up...

Demo works for me, i inspected the issue with console and got following:
![grafik](https://github.com/axeloz/filesharing/assets/94435104/ffb6896f-a9c2-4dce-980e-c84f29449090)
So there is a missing permission, i probably need to use chmod somewhere but i don't really know where xD

Regards,
FuckingToasters
