### ISSUE TITLE
error : permission denied

### ISSUE THREAD

**Issue by RisedSky** [axeloz/filesharing#49]
Hello i have a permission denied on the cosnole of my web page.
I tried with a volume, with changing the user and mounting a local directory, can you provide me some advice to made your container work ? (i don't have any problem with others container)

**Comment by axeloz** [comment]
You did try to `chmod -R 777` your local storage disk, right?

**Comment by RisedSky** [comment]
> You did try to `chmod -R 777` your local storage disk, right?

Yep, i changed the owner id and the group id + chmod
Fixed but that's kinda bad to change the uid and gid, i think you need to midfy the docker file to be able to change it or so.
Also, i tried filesharing and i didn't like the fact there is no preview link directly, instead of viewing on the web page (discord sharing for exemple)

**Comment by axeloz** [comment]
I didn't understand your feedback about the preview link. There is a preview link but I guess this is not what you need

Let me know.

**Comment by theDepart3d** [comment]
I just ran into this same issue. Locally it worked but access via WAN it showed 403 Forbidden.

To get this to work correctly you need the correct permission.

**NEVER EVER SET ANY DIRECTORY THAT IS ACCESSIBLE TO THE WEB AS 777.** - bad security practice

To solve the issue all you have to do is set the correct permission using something like `find`
All I did was the following;
```
find /path/to/the/app -type f -exec chmod 644 {} \;
find /path/to/the/app -type d -exec chmod 755 {} \;
```

The first one; sets all files to 644 and the second one sets all directories to 755 which is correct for any laravel application or web app.

Problem solved and I was able to access it via WAN/Web.

**Comment by axeloz** [comment]
@theDepart3d thanks, you are right for the 777. Bad advise, I wanted to make sure this was a permission related issue. 
Thanks for your message anyways, I'm sure this will help others. 
I will update the readme accordingly.

**Comment by theDepart3d** [comment]
> @theDepart3d thanks, you are right for the 777. Bad advise, I wanted to make sure this was a permission related issue. Thanks for your message anyways, I'm sure this will help others. I will update the readme accordingly.

You could also add that the app folder should match with the apache2/nginx user

`chown -R www-data:www-data /path/to/app/dir
