### ISSUE TITLE
i can not login

### ISSUE THREAD

**Issue by kia1349** [axeloz/filesharing#53]
Hello
thanks for this script
i installed step by step your script on my local host
when i go to http://localhost/filesharing/public/
When I go to the address  http://localhost/filesharing/public/  it does not show any reaction
And it shows this message in the console:

       POST http://localhost/login 404 (Not Found)

I have even set   APP_URL="http://localhost/filesharing/public"   in the .env file

![Screenshot from 2024-01-03 15-52-00](https://github.com/axeloz/filesharing/assets/10990724/0200c752-7c9a-4855-9c5c-995fa0d48e04)

**Comment by axeloz** [comment]
Hello, 
that's because you are using the /public path I guess. 
You should create a virtual host and change the DOCUMENT ROOT in this virtualhost to /public.
Are you using Apache?

Other option: use docker, that should work out-of-the-box.

**Comment by axeloz** [comment]
@kia1349 this commit should fix your issue
https://github.com/axeloz/filesharing/commit/b41816326939c50484521e842d89e855a08f5292

**Comment by kia1349** [comment]
> Hello, that's because you are using the /public path I guess. You should create a virtual host and change the DOCUMENT ROOT in this virtualhost to /public. Are you using Apache?
> 
> Other option: use docker, that should work out-of-the-box.
> 
> EDIT: the app expects to be at the root URL. For instance: http://filesharing.local/ I should fix this

yes ,thank you
i solved problem whit your help
