### ISSUE TITLE
Request for new release

### ISSUE THREAD

**Issue by mluex** [axeloz/filesharing#65]
Hi, thank you so much for your efforts! Your application looks great and exactly what I am looking for.

However, I am struggling with deploying it behind an Nginx reverse proxy (Nginx Proxy Manager).
I've found out that this commit here will solve my problem: [2fdca6b](https://github.com/axeloz/filesharing/commit/2fdca6b0c730c0ea8f0f6ebe5d8e2b55a7392e02)

Would it be possible for you to tag a new release and update the Docker image? That would be great! <3

**Comment by axeloz** [comment]
Hello, you are right, forgot to merge and deploy. Will do now. Thanks

**Comment by axeloz** [comment]
@mluex it's deployed!
Let me know if ok for you.
Thanks
